documents = [
    {
        "name":"Python基础",
        "category":"编程",
        "score":0.9
    },
    {
        "name":"Git教程",
        "category":"工具",
        "score":0.7
    },
    {
        "name":"RAG原理",
        "category":"AI",
        "score":0.95
    },
    {
        "name":"Agent开发",
        "category":"AI",
        "score":0.85
    }
]